// ============================================================
// CANONICAL CONFIGURATION PARAMETERS & VALIDATION REGISTRY
// Phase 2C Server Baseline Configuration Dataset & Business Conflict Map
// ============================================================

export interface CanonicalConfigParam {
  key: string;
  name: string;
  description?: string;
  category: string;
  value: any;
  unit: string;
  valueType: 'number' | 'string' | 'boolean' | 'json';
  minimum?: number;
  maximum?: number;
  location?: string;
  specificationTier?: string;
  source: string;
  isStatutory?: boolean;
}

export interface ConflictDefinition {
  key: string;
  name: string;
  effectiveValue: any;
  alternateValue: any;
  unit: string;
  reason: string;
  status: 'CONFLICT_REQUIRES_REVIEW';
}

export const CANONICAL_BASELINE_VERSION = {
  versionNumber: 'v1.0.0',
  status: 'ACTIVE',
  changeNote: 'Authoritative Baseline Configuration v1.0.0 established from Hutty Phase 2B/2C Architecture.',
  createdBy: 'Hutty Engineering',
  publishedBy: 'Chief Quantity Surveyor',
  effectiveFrom: new Date('2026-01-01T00:00:00.000Z'),
};

export const KNOWN_CONFLICT_REGISTRY: ConflictDefinition[] = [
  {
    key: 'config.paint.interior_coverage_sqft_per_litre',
    name: 'Interior Paint Coverage',
    effectiveValue: 45,
    alternateValue: 60,
    unit: 'sqft/L',
    reason: 'Current engine assumes 45 sqft/L for 2 coats premium emulsion; earlier spec referenced 60 sqft/L.',
    status: 'CONFLICT_REQUIRES_REVIEW',
  },
  {
    key: 'config.commercial.contractor_margin',
    name: 'Contractor Execution Margin',
    effectiveValue: 15,
    alternateValue: 10,
    unit: '%',
    reason: 'Baseline config uses 15% for turnkey; contractor mode target is 8-10% and direct self-build is 0%.',
    status: 'CONFLICT_REQUIRES_REVIEW',
  },
  {
    key: 'config.waterproofing.sump_surface_sqft',
    name: 'Underground Sump Waterproofing Surface',
    effectiveValue: 120,
    alternateValue: 180,
    unit: 'sqft',
    reason: 'Current code uses 120 sqft; standard 8,000L rectangular sump geometry is ~180 sqft.',
    status: 'CONFLICT_REQUIRES_REVIEW',
  },
  {
    key: 'config.flooring.circulation_allowance_pct',
    name: 'Livable Circulation Allowance',
    effectiveValue: 10,
    alternateValue: 14,
    unit: '%',
    reason: 'Code uses 10% circulation tile allowance; architectural standard for duplex is 12-15%.',
    status: 'CONFLICT_REQUIRES_REVIEW',
  },
  {
    key: 'config.flooring.staircase_granite_sqft_flight',
    name: 'Staircase Granite Slab Allowance',
    effectiveValue: 180,
    alternateValue: 175,
    unit: 'sqft/flight',
    reason: 'Code rounds to 180 sqft; geometric calculation for 18 steps (11"x42" + 6.5"x42") is 175.8 sqft.',
    status: 'CONFLICT_REQUIRES_REVIEW',
  },
];

export const CANONICAL_CONFIG_PARAMETERS: CanonicalConfigParam[] = [
  // ── Structural & RCC ──
  {
    key: 'config.structure.wall_height_ft',
    name: 'Standard Clear Wall Height',
    description: 'Floor to ceiling clear wall height consumed across all wall and paint calculations.',
    category: 'RCC_STRUCTURE',
    value: 10.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 8.0,
    maximum: 14.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Pilot Spec / NBC 2016 Guidelines',
  },
  {
    key: 'config.planning.super_bua_multiplier',
    name: 'Super Built-up Area Factor',
    description: 'Super Built-up area multiplier on livable BUA.',
    category: 'BUA_SETBACKS',
    value: 1.15,
    unit: 'multiplier',
    valueType: 'number',
    minimum: 1.0,
    maximum: 1.3,
    location: 'Global',
    specificationTier: 'Global',
    source: 'BBMP / MUDA Planning Norms',
  },
  {
    key: 'config.planning.default_coverage_ratio',
    name: 'Default Ground Coverage Ratio',
    description: 'Maximum allowable ground footprint coverage ratio.',
    category: 'BUA_SETBACKS',
    value: 0.60,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.40,
    maximum: 0.85,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Karnataka Municipal Planning Norms',
  },
  {
    key: 'config.rcc.steel_base_factor_kg_sqft',
    name: 'Base Steel Reinforcement Factor',
    description: 'Ground floor structural steel rebar consumption thumb rule per sqft.',
    category: 'RCC_STRUCTURE',
    value: 2.80,
    unit: 'kg/sqft',
    valueType: 'number',
    minimum: 2.0,
    maximum: 4.5,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 456 Structural Schedule (Ground)',
  },
  {
    key: 'config.rcc.steel_additional_floor_factor',
    name: 'Steel Additional Floor Increment',
    description: 'Incremental steel consumption per upper floor per sqft.',
    category: 'RCC_STRUCTURE',
    value: 0.20,
    unit: 'kg/sqft/floor',
    valueType: 'number',
    minimum: 0.10,
    maximum: 0.50,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 456 Multi-storey Column Schedule',
  },

  // ── Direct Materials ──
  {
    key: 'config.material.cement_bags_per_sqft',
    name: 'Cement Consumption Thumb Rule',
    description: 'Baseline 53-grade / PPC cement consumption in 50kg bags per sqft BUA.',
    category: 'DIRECT_MATERIALS',
    value: 0.40,
    unit: 'bags/sqft',
    valueType: 'number',
    minimum: 0.30,
    maximum: 0.55,
    location: 'Global',
    specificationTier: 'Global',
    source: 'CPWD DSR 2021 Analysis of Rates',
  },
  {
    key: 'config.material.m_sand_cft_per_sqft',
    name: 'Manufactured M-Sand Thumb Rule',
    description: 'Concrete fine aggregate (M-Sand) requirement in CFT per sqft BUA.',
    category: 'DIRECT_MATERIALS',
    value: 0.60,
    unit: 'CFT/sqft',
    valueType: 'number',
    minimum: 0.45,
    maximum: 0.80,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 383 Aggregate Specification',
  },
  {
    key: 'config.material.p_sand_cft_per_sqft',
    name: 'Plastering P-Sand Thumb Rule',
    description: 'Plastering fine sand (P-Sand) requirement in CFT per sqft BUA.',
    category: 'DIRECT_MATERIALS',
    value: 0.60,
    unit: 'CFT/sqft',
    valueType: 'number',
    minimum: 0.45,
    maximum: 0.80,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 1542 Plaster Sand Specification',
  },
  {
    key: 'config.material.coarse_aggregate_cft_per_sqft',
    name: 'Coarse Aggregate Thumb Rule',
    description: '20mm & 12mm crushed blue metal granite coarse aggregate in CFT per sqft BUA.',
    category: 'DIRECT_MATERIALS',
    value: 1.35,
    unit: 'CFT/sqft',
    valueType: 'number',
    minimum: 1.00,
    maximum: 1.80,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 456 M20/M25 Concrete Mix Proportions',
  },

  // ── Masonry ──
  {
    key: 'config.masonry.external_wall_thickness_m',
    name: 'External Masonry Wall Thickness',
    description: 'Nominal thickness of loadbearing / perimeter blockwork (6 inches).',
    category: 'MASONRY',
    value: 0.150,
    unit: 'm',
    valueType: 'number',
    minimum: 0.100,
    maximum: 0.250,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Residential Blockwork',
  },
  {
    key: 'config.masonry.internal_wall_thickness_m',
    name: 'Internal Partition Wall Thickness',
    description: 'Nominal thickness of interior partition blockwork (4 inches).',
    category: 'MASONRY',
    value: 0.100,
    unit: 'm',
    valueType: 'number',
    minimum: 0.075,
    maximum: 0.150,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Partition Blockwork',
  },
  {
    key: 'config.masonry.aac_block_unit_volume_cum',
    name: 'AAC Block Unit Volume',
    description: 'Unit gross volume of 600x200x150mm autoclaved aerated concrete block in cu.m.',
    category: 'MASONRY',
    value: 0.018,
    unit: 'cum/block',
    valueType: 'number',
    minimum: 0.005,
    maximum: 0.030,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Birla Aerocon / Magicrete Dimensions',
  },
  {
    key: 'config.masonry.clay_brick_unit_volume_cum',
    name: 'Clay Brick Unit Volume',
    description: 'Unit volume of standard 190x90x90mm wire-cut modular clay brick in cu.m.',
    category: 'MASONRY',
    value: 0.001539,
    unit: 'cum/brick',
    valueType: 'number',
    minimum: 0.0010,
    maximum: 0.0030,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 1077 Common Burnt Clay Bricks',
  },
  {
    key: 'config.masonry.concrete_block_unit_volume_cum',
    name: 'Solid Concrete Block Unit Volume',
    description: 'Unit gross volume of standard 400x200x150mm dense concrete block in cu.m.',
    category: 'MASONRY',
    value: 0.012,
    unit: 'cum/block',
    valueType: 'number',
    minimum: 0.005,
    maximum: 0.025,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 2185 Solid Concrete Blocks',
  },

  // ── Finishes & Cladding ──
  {
    key: 'config.cladding.bathroom_dado_standard_ft',
    name: 'Bathroom Standard Dado Height',
    description: 'Standard bathroom wall tile cladding height up to 7ft lintel level.',
    category: 'FINISHES',
    value: 7.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 5.0,
    maximum: 8.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Standard Architectural Spec',
  },
  {
    key: 'config.cladding.bathroom_dado_full_ft',
    name: 'Bathroom Full Ceiling Dado Height',
    description: 'Full ceiling height wall tile cladding in bathrooms (10ft).',
    category: 'FINISHES',
    value: 10.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 8.0,
    maximum: 12.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Luxury Architectural Spec',
  },
  {
    key: 'config.cladding.kitchen_dado_standard_ft',
    name: 'Kitchen Standard Dado Height',
    description: 'Backsplash ceramic tile height above granite countertop (2ft).',
    category: 'FINISHES',
    value: 2.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 1.5,
    maximum: 3.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Standard Architectural Spec',
  },
  {
    key: 'config.cladding.kitchen_dado_extended_ft',
    name: 'Kitchen Extended Dado Height',
    description: 'Extended full-wall ceramic tile backsplash in kitchen (4ft).',
    category: 'FINISHES',
    value: 4.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 3.0,
    maximum: 6.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Premium Architectural Spec',
  },
  {
    key: 'config.cladding.kitchen_counter_length_ft',
    name: 'Standard Kitchen Counter Length',
    description: 'Estimated linear running length of kitchen granite counter slab.',
    category: 'FINISHES',
    value: 15.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 8.0,
    maximum: 25.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Residential Kitchen Layout',
  },
  {
    key: 'config.flooring.circulation_allowance_pct',
    name: 'Livable Circulation Allowance',
    description: 'Corridor, hallway and lobby circulation allowance percentage on livable BUA.',
    category: 'FINISHES',
    value: 10,
    unit: '%',
    valueType: 'number',
    minimum: 5,
    maximum: 18,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Flooring Estimator',
  },
  {
    key: 'config.flooring.staircase_granite_sqft_flight',
    name: 'Staircase Granite Allowance',
    description: 'Granite slab surface area for treads, risers and landings per staircase flight.',
    category: 'FINISHES',
    value: 180,
    unit: 'sqft/flight',
    valueType: 'number',
    minimum: 120,
    maximum: 250,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Staircase Estimator (18 steps)',
  },

  // ── Waterproofing ──
  {
    key: 'config.waterproofing.bathroom_upturn_ft',
    name: 'Bathroom Waterproofing Upturn Height',
    description: 'Vertical wall upturn height for elastomeric waterproofing membrane (1ft / 300mm).',
    category: 'WATERPROOFING',
    value: 1.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 0.5,
    maximum: 2.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 3067 Code of Practice for Waterproofing',
  },
  {
    key: 'config.waterproofing.balcony_upturn_ft',
    name: 'Balcony Waterproofing Upturn Height',
    description: 'Perimeter curb upturn height for balcony waterproofing (6 inches).',
    category: 'WATERPROOFING',
    value: 0.5,
    unit: 'ft',
    valueType: 'number',
    minimum: 0.25,
    maximum: 1.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Hutty Waterproofing Estimator',
  },
  {
    key: 'config.waterproofing.terrace_coverage_ratio',
    name: 'Terrace Waterproofing Coverage Ratio',
    description: 'Ratio of roof slab receiving Brick Bat Coba / acrylic waterproofing.',
    category: 'WATERPROOFING',
    value: 1.00,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.80,
    maximum: 1.10,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Flat Roof Practice',
  },
  {
    key: 'config.waterproofing.sump_surface_sqft',
    name: 'Underground Sump Waterproofing Surface',
    description: 'Internal plaster + chemical membrane surface area for underground RCC water sump.',
    category: 'WATERPROOFING',
    value: 120,
    unit: 'sqft',
    valueType: 'number',
    minimum: 80,
    maximum: 250,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Residential Sump (6000-8000L)',
  },

  // ── Paint & Consumables ──
  {
    key: 'config.paint.interior_coverage_sqft_per_litre',
    name: 'Interior Paint Coverage',
    description: 'Spread rate for 2 coats of interior acrylic emulsion.',
    category: 'PAINT_CONSUMABLES',
    value: 45,
    unit: 'sqft/L',
    valueType: 'number',
    minimum: 35,
    maximum: 65,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Asian Paints Technical Data Sheet (2 coats)',
  },
  {
    key: 'config.paint.exterior_coverage_sqft_per_litre',
    name: 'Exterior Paint Coverage',
    description: 'Spread rate for 2 coats of weather-proof exterior emulsion.',
    category: 'PAINT_CONSUMABLES',
    value: 60,
    unit: 'sqft/L',
    valueType: 'number',
    minimum: 45,
    maximum: 80,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Asian Paints Apex Ultima Technical Data',
  },
  {
    key: 'config.paint.putty_consumption_kg_sqft',
    name: 'Wall Putty Consumption Rate',
    description: 'Polymer white wall putty consumption for 2 smooth coats.',
    category: 'PAINT_CONSUMABLES',
    value: 0.55,
    unit: 'kg/sqft',
    valueType: 'number',
    minimum: 0.40,
    maximum: 0.80,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Birla White WallSeal Data Sheet',
  },

  // ── Electrical MEP ──
  {
    key: 'config.electrical.wire_1_5_m_per_point',
    name: '1.5 sq.mm Wire per Light/Fan Point',
    description: 'Average conduit run for 1.5 sq.mm phase, neutral & earth wires per lighting point.',
    category: 'ELECTRICAL',
    value: 8.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 6.0,
    maximum: 14.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 732 Wiring Installations',
  },
  {
    key: 'config.electrical.wire_2_5_m_per_point',
    name: '2.5 sq.mm Wire per Socket Point',
    description: 'Conduit run for 2.5 sq.mm conductors feeding 6A/16A standard power socket points.',
    category: 'ELECTRICAL',
    value: 12.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 9.0,
    maximum: 18.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 732 Wiring Installations',
  },
  {
    key: 'config.electrical.wire_4_0_m_per_point',
    name: '4.0 sq.mm Wire per AC/Geyser Point',
    description: 'Dedicated homerun circuit cable length for 25A heavy appliance points.',
    category: 'ELECTRICAL',
    value: 22.0,
    unit: 'm/point',
    valueType: 'number',
    minimum: 15.0,
    maximum: 30.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 732 Wiring Installations',
  },
  {
    key: 'config.electrical.riser_wire_6_0_m_floor',
    name: '6.0 sq.mm Vertical Sub-Main Cable',
    description: 'Vertical riser sub-main conductors from main panel to floor distribution board.',
    category: 'ELECTRICAL',
    value: 35.0,
    unit: 'm/floor',
    valueType: 'number',
    minimum: 20.0,
    maximum: 50.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Central Power Distribution Schedule',
  },
  {
    key: 'config.electrical.ev_wire_6_0_m',
    name: '6.0 sq.mm EV Charger Circuit',
    description: 'Dedicated heavy feeder cable run for 7.4kW EV wallbox charger.',
    category: 'ELECTRICAL',
    value: 35.0,
    unit: 'm',
    valueType: 'number',
    minimum: 20.0,
    maximum: 50.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'EVSE Installation Benchmark',
  },
  {
    key: 'config.electrical.conduit_m_per_point',
    name: 'Conduit per Electrical Point',
    description: 'Heavy duty 25mm PVC concealed conduit length per electrical terminal.',
    category: 'ELECTRICAL',
    value: 2.6,
    unit: 'm/point',
    valueType: 'number',
    minimum: 1.8,
    maximum: 4.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'National Electrical Code (NEC)',
  },
  {
    key: 'config.electrical.conduit_riser_m_floor',
    name: 'Vertical Shaft Conduit per Floor',
    description: 'Heavy gauge riser conduit in electrical duct per floor.',
    category: 'ELECTRICAL',
    value: 15.0,
    unit: 'm/floor',
    valueType: 'number',
    minimum: 10.0,
    maximum: 25.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'NEC Riser Allowance',
  },
  {
    key: 'config.electrical.switch_modules_ratio',
    name: 'Modular Switch Plates Multiplier',
    description: 'Gang box modules ratio per electrical point.',
    category: 'ELECTRICAL',
    value: 0.75,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.50,
    maximum: 1.20,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Modular Wiring Standard',
  },

  // ── Plumbing MEP ──
  {
    key: 'config.plumbing.cpvc_m_per_point',
    name: 'CPVC Supply Pipe per Water Point',
    description: 'SDR 11 CPVC hot/cold distribution pipe run per plumbing fixture point.',
    category: 'PLUMBING',
    value: 4.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 3.0,
    maximum: 7.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Uniform Plumbing Code (UPC-India)',
  },
  {
    key: 'config.plumbing.swr_m_per_point',
    name: 'SWR Drainage Pipe per Drain Point',
    description: 'Rigid PVC / SWR wastewater and soil discharge pipe per drainage point.',
    category: 'PLUMBING',
    value: 3.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 2.5,
    maximum: 5.5,
    location: 'Global',
    specificationTier: 'Global',
    source: 'UPC-India Sanitary Drainage',
  },
  {
    key: 'config.plumbing.riser_m_per_floor',
    name: 'Vertical Plumbing Stack Riser',
    description: 'Vertical SWR soil and vent stack pipe length per floor in plumbing shaft.',
    category: 'PLUMBING',
    value: 12.0,
    unit: 'm/floor',
    valueType: 'number',
    minimum: 8.0,
    maximum: 20.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Plumbing Stack Norms',
  },
  {
    key: 'config.plumbing.daily_water_demand_lpcd',
    name: 'Daily Domestic Demand per Person',
    description: 'Statutory daily per-capita domestic water consumption standard (IS 1172).',
    category: 'PLUMBING',
    value: 135,
    unit: 'LPCD',
    valueType: 'number',
    minimum: 100,
    maximum: 200,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 1172 Domestic Water Consumption',
  },
  {
    key: 'config.plumbing.water_storage_reserve_days',
    name: 'Water Storage Reserve Buffer',
    description: 'Days of municipal/borewell reserve storage required.',
    category: 'PLUMBING',
    value: 1.5,
    unit: 'days',
    valueType: 'number',
    minimum: 1.0,
    maximum: 3.0,
    location: 'Global',
    specificationTier: 'Global',
    source: 'NBC 2016 Water Supply',
  },
  {
    key: 'config.plumbing.occupants_per_bedroom',
    name: 'Bedroom Occupancy Proxy',
    description: 'Headcount assumption per planned bedroom for storage sizing.',
    category: 'PLUMBING',
    value: 2.0,
    unit: 'persons',
    valueType: 'number',
    minimum: 1.5,
    maximum: 3.5,
    location: 'Global',
    specificationTier: 'Global',
    source: 'NBC 2016 Residential Occupancy',
  },

  // ── Commercial Margins & Rules ──
  {
    key: 'config.commercial.contractor_margin',
    name: 'Contractor Execution Margin',
    description: 'Overhead and profit margin applied in turnkey builder contracts.',
    category: 'COMMERCIAL',
    value: 15,
    unit: '%',
    valueType: 'number',
    minimum: 0,
    maximum: 25,
    location: 'Global',
    specificationTier: 'Global',
    source: 'CPWD Works Manual / Market Standard',
  },
  {
    key: 'config.commercial.professional_fees',
    name: 'Architectural & Engineering Fees',
    description: 'Design, structural engineering, and statutory sanction consultation fees.',
    category: 'COMMERCIAL',
    value: 5,
    unit: '%',
    valueType: 'number',
    minimum: 2,
    maximum: 10,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Council of Architecture (COA) Guidelines',
  },
  {
    key: 'config.commercial.contingency',
    name: 'Unforeseen Contingency Reserve',
    description: 'Risk escalation and site condition reserve margin.',
    category: 'COMMERCIAL',
    value: 6,
    unit: '%',
    valueType: 'number',
    minimum: 3,
    maximum: 12,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Quantity Surveying Practice',
  },
  {
    key: 'config.commercial.gst_rate',
    name: 'Works Contract GST',
    description: 'Goods and Services Tax on residential composite construction contracts.',
    category: 'COMMERCIAL',
    value: 18,
    unit: '%',
    valueType: 'number',
    minimum: 0,
    maximum: 28,
    location: 'Global',
    specificationTier: 'Global',
    source: 'GST Council Notification No. 03/2022',
  },

  // ── Wastage Factors ──
  {
    key: 'config.wastage.steel',
    name: 'Reinforcement Steel Cutting Wastage',
    description: 'Lapping, cut piece and binding wire loss allowance.',
    category: 'WASTAGE',
    value: 5,
    unit: '%',
    valueType: 'number',
    minimum: 2,
    maximum: 10,
    location: 'Global',
    specificationTier: 'Global',
    source: 'IS 2502 Bending and Fixing of Bars',
  },
  {
    key: 'config.wastage.cement',
    name: 'Cement Handling & Slurry Wastage',
    description: 'Transit loss, torn bags and batching wastage.',
    category: 'WASTAGE',
    value: 2,
    unit: '%',
    valueType: 'number',
    minimum: 1,
    maximum: 5,
    location: 'Global',
    specificationTier: 'Global',
    source: 'CPWD Analysis of Rates',
  },
  {
    key: 'config.wastage.masonry',
    name: 'Masonry Block Cutting Wastage',
    description: 'Chipping, corner cutting and half-block bonding loss.',
    category: 'WASTAGE',
    value: 5,
    unit: '%',
    valueType: 'number',
    minimum: 2,
    maximum: 10,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Standard Masonry Norms',
  },
  {
    key: 'config.wastage.flooring',
    name: 'Flooring Tile Cutting Wastage',
    description: 'Edge diagonal cuts, skirting and breakage allowance.',
    category: 'WASTAGE',
    value: 7,
    unit: '%',
    valueType: 'number',
    minimum: 3,
    maximum: 12,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Tile Laying Practice (IS 1443)',
  },
  {
    key: 'config.wastage.paint',
    name: 'Paint & Plaster Wastage',
    description: 'Roller spatter, tray loss and surface absorption factor.',
    category: 'WASTAGE',
    value: 10,
    unit: '%',
    valueType: 'number',
    minimum: 5,
    maximum: 18,
    location: 'Global',
    specificationTier: 'Global',
    source: 'Finishing Works Estimating Norm',
  },
];
