// ============================================================
// WINDOWS MODULE – Authoritative Window Engine & Fenestration Schedule
// Strictly follows Hutty Pilot Specification (Section 14)
//
// Rules:
// - Window requirements generated by room space rules
// - Frame / Shutter / Grill area calculated from space openings
// - Consumed identically across wall deductions, plaster, paint, BOQ & fixtures
// ============================================================

import { EngineInput, WindowScheduleItem } from '../types';
import { getBrandRate } from '../data/brandDatabase';
import { rateService } from '../data/rateService';

export function calculateWindows(input: EngineInput): {
  windowsCount: number;
  windowAreaSqFt: number;
  grillAreaSqFt: number;
  windowSchedule: WindowScheduleItem[];
} {
  const { rooms, floors, windows, materialBrands } = input;
  const isZero = (!floors || floors <= 0) && (!input.plotLength || input.plotLength <= 0);

  if (isZero) {
    return {
      windowsCount: 0,
      windowAreaSqFt: 0,
      grillAreaSqFt: 0,
      windowSchedule: [],
    };
  }

  // 1. Calculate room-driven windows
  const bedCount = rooms.bedrooms || 0;
  const livingCount = (rooms.living || 0) * 2; // 2 picture windows for living
  const kitchenCount = rooms.kitchen || 0;
  const bathCount = (rooms.bathrooms || 0) + (rooms.commonToilets || 0);
  const diningCount = rooms.dining || 0;
  const officeCount = rooms.office || 0;
  const utilityCount = rooms.utility || 0;

  const windowsCount = bedCount + livingCount + kitchenCount + bathCount + diningCount + officeCount + utilityCount;

  const bedArea = bedCount * 20; // 5×4 ft
  const livingArea = livingCount * 30; // 6×5 ft
  const kitchenArea = kitchenCount * 12; // 4×3 ft
  const bathArea = bathCount * 6; // 2×3 ft louvred ventilator
  const diningArea = diningCount * 15; // 5×3 ft
  const officeArea = officeCount * 15; // 5×3 ft
  const utilityArea = utilityCount * 8; // 4×2 ft

  const windowAreaSqFt = bedArea + livingArea + kitchenArea + bathArea + diningArea + officeArea + utilityArea;
  const grillAreaSqFt = Math.round(windowAreaSqFt * 0.75); // 75% windows have MS safety grilles

  // 2. Resolve Rate
  const prim = windows?.primaryMaterial || 'uPVC';
  const sub = windows?.subGrade || 'Standard uPVC';
  let defaultWindowRate = 650;

  if (prim === 'uPVC') {
    if (sub === 'Luxury / Fenesta uPVC' || materialBrands?.windows === 'Fenesta uPVC') defaultWindowRate = 850;
    else if (sub === 'Standard uPVC') defaultWindowRate = 550;
    else defaultWindowRate = 650;
  } else if (prim === 'Wood') {
    if (sub === 'Teak Wood Frame') defaultWindowRate = 950;
    else if (sub === 'Sal Frame / Honne Shutter') defaultWindowRate = 680;
    else defaultWindowRate = 850;
  } else if (prim === 'Aluminium') {
    if (sub === 'Powder Coated Jindal Aluminium') defaultWindowRate = 620;
    else if (sub === 'Anodized Aluminium') defaultWindowRate = 480;
    else defaultWindowRate = 520;
  } else if (materialBrands?.windows) {
    defaultWindowRate = getBrandRate('windows', materialBrands.windows) || defaultWindowRate;
  }

  const winBrand = materialBrands?.windows || sub;
  const windowRate = rateService.getEffectiveRate(
    'windows.upvc_standard',
    { packageTier: input.qualityTier, location: input.city, brand: winBrand },
    defaultWindowRate
  );

  // 3. Authoritative Schedule
  const schedule: WindowScheduleItem[] = [];

  const addWin = (code: string, desc: string, spaceType: string, count: number, widthFt: number, heightFt: number) => {
    if (count <= 0) return;
    const unitArea = widthFt * heightFt;
    const totalArea = count * unitArea;
    const size = `${widthFt.toFixed(1)} ft × ${heightFt.toFixed(1)} ft`;
    schedule.push({
      code,
      description: desc,
      spaceType,
      count,
      widthFt,
      heightFt,
      unitAreaSqFt: unitArea,
      totalOpeningAreaSqFt: totalArea,
      totalAreaSqFt: totalArea,
      quantity: totalArea,
      unit: 'Sq Ft',
      openingSize: size,
      openingAreaSqFt: unitArea,
      frameAreaSqFt: totalArea,
      shutterAreaSqFt: totalArea,
      grillAreaSqFt: Math.round(totalArea * 0.8),
      material: prim,
      specification: `${prim} – ${sub}`,
      unitRate: windowRate,
      amount: totalArea * windowRate,
    });
  };

  addWin('W-BED', 'Bedroom 2-Track Glazed Window with Mosquito Mesh', 'Bedrooms', bedCount, 5.0, 4.0);
  addWin('W-LIV', 'Living Room 3-Track Picture Window (Full Height)', 'Living Room', livingCount, 6.0, 5.0);
  addWin('W-KIT', 'Kitchen Sliding Window with Exhaust Louver Provision', 'Kitchen', kitchenCount, 4.0, 3.0);
  addWin('W-BATH', 'Bathroom Louvered Ventilator with Exhaust Opening', 'Bathrooms / Toilets', bathCount, 2.0, 3.0);
  addWin('W-DIN', 'Dining Room Glazed Sliding Window', 'Dining Area', diningCount, 5.0, 3.0);
  addWin('W-OFF', 'Study / Office Natural Light Window', 'Home Office', officeCount, 5.0, 3.0);
  addWin('W-UTL', 'Utility Service Ventilator Window', 'Utility Area', utilityCount, 4.0, 2.0);

  return {
    windowsCount,
    windowAreaSqFt,
    grillAreaSqFt,
    windowSchedule: schedule,
  };
}
