// ============================================================
// HUTTY BASELINE CONFIGURATION DATASET (v1.0.0)
// Establishes the authoritative active baseline configuration for all
// calculation parameters, room templates, commercial rules, and benchmarks.
// ============================================================

import {
  CalculationParameter,
  SpaceTemplateConfig,
  CommercialRuleConfig,
  LabourBenchmarkConfig,
  ConfigurationVersion,
} from './types';
import { ROOM_SIZE_ASSUMPTIONS } from '../data/engineeringAssumptions';

export const HUTTY_BASELINE_VERSION: ConfigurationVersion = {
  id: 'cfg-ver-1.0.0',
  versionNumber: 'v1.0.0',
  status: 'ACTIVE',
  createdBy: 'Hutty Engineering',
  createdAt: '2026-01-01T00:00:00.000Z',
  publishedBy: 'Chief Quantity Surveyor',
  publishedAt: '2026-01-01T00:00:00.000Z',
  effectiveFrom: '2026-01-01T00:00:00.000Z',
  changeNote: 'Baseline Production Configuration v1.0.0 established from Hutty Pilot Specification & Sept 19 Review.',
  validationStatus: 'VALID',
  parametersCount: 38,
};

export const HUTTY_BASELINE_PARAMETERS: CalculationParameter[] = [
  // ── 1. Planning & Geometry ──
  {
    id: 'p-wall-height',
    key: 'config.structure.wall_height_ft',
    name: 'Standard Clear Wall Height',
    description: 'Floor to ceiling clear wall height consumed across all wall and paint calculations.',
    category: 'RCC_STRUCTURE',
    value: 10.0,
    unit: 'ft',
    valueType: 'number',
    minimum: 8.0,
    maximum: 14.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec / NBC 2016 Guidelines',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-super-bua',
    key: 'config.planning.super_bua_multiplier',
    name: 'Super Built-up Area Factor',
    description: 'Super Built-up area multiplier on livable BUA.',
    category: 'BUA_SETBACKS',
    value: 1.15,
    unit: 'multiplier',
    valueType: 'number',
    minimum: 1.0,
    maximum: 1.35,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Standard Real Estate Planning Norm',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-coverage-factor',
    key: 'config.planning.default_coverage_ratio',
    name: 'Ground Coverage Factor (Fallback)',
    description: 'Default maximum ground coverage when setbacks are not explicitly configured.',
    category: 'BUA_SETBACKS',
    value: 0.60,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.40,
    maximum: 0.85,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'BBMP / BDA / MUDA By-laws Benchmark',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 2. Structural Steel Thumb Rules ──
  {
    id: 'p-steel-base',
    key: 'config.rcc.steel_base_factor_kg_sqft',
    name: 'Base Steel Consumption Factor (Ground Floor)',
    description: 'Starting steel rebar factor in kg per sqft BUA.',
    category: 'RCC_STRUCTURE',
    value: 2.8,
    unit: 'kg/sqft',
    valueType: 'number',
    minimum: 2.0,
    maximum: 4.5,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 6)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-steel-floor-incr',
    key: 'config.rcc.steel_additional_floor_factor',
    name: 'Steel Additional Floor Factor',
    description: 'Rebar factor increment per upper floor (+0.2 kg/sqft per floor above ground).',
    category: 'RCC_STRUCTURE',
    value: 0.2,
    unit: 'kg/sqft/floor',
    valueType: 'number',
    minimum: 0.1,
    maximum: 0.5,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 6)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-steel-wastage',
    key: 'config.wastage.steel',
    name: 'Steel Cutting & Lapping Wastage',
    description: 'IS 2502 standard cutting, bending, and lapping allowance.',
    category: 'WASTAGE_COVERAGE',
    value: 5.0,
    unit: '%',
    valueType: 'number',
    minimum: 2.0,
    maximum: 10.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'IS 2502 Standard Benchmark',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 3. Direct Materials Thumb Rules ──
  {
    id: 'p-cement-factor',
    key: 'config.material.cement_bags_per_sqft',
    name: 'Cement Starting Thumb Rule',
    description: 'Standard 50kg cement bags per sqft of total BUA.',
    category: 'MATERIALS',
    value: 0.40,
    unit: 'bags/sqft',
    valueType: 'number',
    minimum: 0.30,
    maximum: 0.60,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 8)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-msand-factor',
    key: 'config.material.m_sand_cft_per_sqft',
    name: 'M-Sand Starting Thumb Rule',
    description: 'Manufactured M-Sand for RCC concrete fine aggregate.',
    category: 'MATERIALS',
    value: 0.60,
    unit: 'CFT/sqft',
    valueType: 'number',
    minimum: 0.40,
    maximum: 0.85,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 9)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-psand-factor',
    key: 'config.material.p_sand_cft_per_sqft',
    name: 'P-Sand Starting Thumb Rule',
    description: 'Plastering P-Sand for block mortar and 2-coat plaster.',
    category: 'MATERIALS',
    value: 0.60,
    unit: 'CFT/sqft',
    valueType: 'number',
    minimum: 0.40,
    maximum: 0.85,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 10)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-agg-factor',
    key: 'config.material.coarse_aggregate_cft_per_sqft',
    name: 'Coarse Aggregate Thumb Rule',
    description: '20mm and 12mm graded crushed stone aggregate.',
    category: 'MATERIALS',
    value: 1.35,
    unit: 'CFT/sqft',
    valueType: 'number',
    minimum: 1.0,
    maximum: 1.8,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 11)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 4. Paint Consumables ──
  {
    id: 'p-paint-interior',
    key: 'config.paint.interior_coverage_sqft_per_litre',
    name: 'Interior Emulsion Paint Coverage',
    description: 'Effective coverage for 2 coats of interior wall emulsion.',
    category: 'PAINT_PLASTER',
    value: 45.0,
    unit: 'sqft/Litre',
    valueType: 'number',
    minimum: 35.0,
    maximum: 70.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'paint.ts line 65 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-paint-exterior',
    key: 'config.paint.exterior_coverage_sqft_per_litre',
    name: 'Exterior Weather Guard Paint Coverage',
    description: 'Effective coverage for 2 coats of exterior weather-proof paint.',
    category: 'PAINT_PLASTER',
    value: 60.0,
    unit: 'sqft/Litre',
    valueType: 'number',
    minimum: 40.0,
    maximum: 85.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'paint.ts line 66 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-paint-putty',
    key: 'config.paint.putty_consumption_kg_sqft',
    name: 'Acrylic Wall Putty Consumption',
    description: 'Putty consumption rate per sqft for 2 coats.',
    category: 'PAINT_PLASTER',
    value: 0.55,
    unit: 'kg/sqft',
    valueType: 'number',
    minimum: 0.35,
    maximum: 0.85,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'paint.ts line 67 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 5. Flooring & Cladding ──
  {
    id: 'p-floor-wastage',
    key: 'config.wastage.flooring',
    name: 'Flooring Cutting & Pattern Wastage',
    description: 'Standard tile cutting and edge perimeter wastage allowance.',
    category: 'WASTAGE_COVERAGE',
    value: 7.0,
    unit: '%',
    valueType: 'number',
    minimum: 3.0,
    maximum: 15.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 15)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-floor-circulation',
    key: 'config.flooring.circulation_allowance_pct',
    name: 'Livable Circulation Tile Allowance',
    description: 'Passages, corridors, and foyer tile allowance as % of BUA.',
    category: 'FLOORING_FINISHES',
    value: 10.0,
    unit: '%',
    valueType: 'number',
    minimum: 5.0,
    maximum: 20.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'flooring.ts line 54 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-stair-granite',
    key: 'config.flooring.staircase_granite_sqft_flight',
    name: 'Staircase Granite Slabs per Flight',
    description: 'Granite slab square footage for staircase treads, risers, and landings.',
    category: 'FLOORING_FINISHES',
    value: 180.0,
    unit: 'sqft/flight',
    valueType: 'number',
    minimum: 120.0,
    maximum: 250.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'flooring.ts line 74 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 6. Electrical Routing Benchmarks ──
  {
    id: 'p-elec-wire-1-5',
    key: 'config.electrical.wire_1_5_m_per_point',
    name: '1.5 sq.mm Wire per Light/Fan Point',
    description: 'Conductor length in metres for lighting and fan circuits.',
    category: 'ELECTRICAL',
    value: 8.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 6.0,
    maximum: 15.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'electrical.ts line 116 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-elec-wire-2-5',
    key: 'config.electrical.wire_2_5_m_per_point',
    name: '2.5 sq.mm Wire per Socket Point',
    description: 'Conductor length in metres for 6A/16A power socket circuits.',
    category: 'ELECTRICAL',
    value: 12.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 8.0,
    maximum: 20.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'electrical.ts line 120 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-elec-wire-4-0',
    key: 'config.electrical.wire_4_0_m_per_point',
    name: '4.0 sq.mm Wire per Heavy AC/Geyser Point',
    description: 'Conductor length in metres for dedicated heavy appliance homeruns.',
    category: 'ELECTRICAL',
    value: 22.0,
    unit: 'm/point',
    valueType: 'number',
    minimum: 15.0,
    maximum: 32.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'electrical.ts line 124 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-elec-conduit',
    key: 'config.electrical.conduit_m_per_point',
    name: 'PVC Conduit per Electrical Point',
    description: '25mm heavy-duty PVC embedded conduit route length.',
    category: 'ELECTRICAL',
    value: 2.6,
    unit: 'm/point',
    valueType: 'number',
    minimum: 1.8,
    maximum: 4.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'electrical.ts line 149 (Effective Baseline)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 7. Plumbing Routing Benchmarks ──
  {
    id: 'p-plumb-cpvc',
    key: 'config.plumbing.cpvc_m_per_point',
    name: 'CPVC Supply Pipe per Water Point',
    description: 'Hot and cold concealed CPVC distribution line per water fixture.',
    category: 'PLUMBING',
    value: 4.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 3.0,
    maximum: 7.5,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 20)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-plumb-swr',
    key: 'config.plumbing.swr_m_per_point',
    name: 'SWR Drainage Pipe per Drain Point',
    description: 'Soil and waste drainage piping per fixture trap.',
    category: 'PLUMBING',
    value: 3.5,
    unit: 'm/point',
    valueType: 'number',
    minimum: 2.0,
    maximum: 6.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'Hutty Pilot Spec (Section 20)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-plumb-water-demand',
    key: 'config.plumbing.daily_water_demand_lpcd',
    name: 'Daily Water Demand per Person',
    description: 'IS 1172 residential domestic water requirement.',
    category: 'PLUMBING',
    value: 135.0,
    unit: 'LPCD',
    valueType: 'number',
    minimum: 100.0,
    maximum: 200.0,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'IS 1172 Standard Code of Basic Water Requirements',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },

  // ── 8. Commercial Baseline Additions ──
  {
    id: 'p-comm-margin',
    key: 'config.commercial.contractor_margin',
    name: 'Contractor Overhead & Execution Margin',
    description: 'Contractor margin applied when Contractor Mode is enabled.',
    category: 'COMMERCIAL',
    value: 0.15,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.0,
    maximum: 0.30,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'HUTTY_BASELINE_CONFIG in rateMasterDefaults.ts',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-comm-contingency',
    key: 'config.commercial.contingency',
    name: 'Contingency Reserve Buffer',
    description: 'Price escalation and unexpected subsurface contingency allowance.',
    category: 'COMMERCIAL',
    value: 0.06,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.0,
    maximum: 0.15,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'HUTTY_BASELINE_CONFIG in rateMasterDefaults.ts',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-comm-prof-fees',
    key: 'config.commercial.professional_fees',
    name: 'Professional Architecture & Engineering Fees',
    description: 'Architectural drawings, structural engineering, and site visit supervision.',
    category: 'COMMERCIAL',
    value: 0.05,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.0,
    maximum: 0.12,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'HUTTY_BASELINE_CONFIG in rateMasterDefaults.ts',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'p-comm-gst',
    key: 'config.commercial.gst_rate',
    name: 'Works Contract GST Rate',
    description: 'GST rate on construction works contract.',
    category: 'COMMERCIAL',
    value: 0.18,
    unit: 'ratio',
    valueType: 'number',
    minimum: 0.0,
    maximum: 0.28,
    location: 'ALL',
    specificationTier: 'ALL',
    source: 'GST Council Notification (18% standard)',
    status: 'ACTIVE',
    version: 'v1.0.0',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const HUTTY_BASELINE_SPACE_TEMPLATES: Record<string, SpaceTemplateConfig> = {
  bedroom: {
    spaceType: 'bedroom',
    name: 'Standard Bedroom',
    defaultLengthFt: 14.0,
    defaultWidthFt: 10.0,
    defaultAreaSqFt: 140.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 1,
    windowAreaSqFt: 20.0,
    doorOpeningAreaSqFt: 21.0,
    lightPoints: 3,
    fanPoints: 1,
    socketPoints: 4,
    acPoints: 1,
    geyserPoints: 0,
    tvDataPoints: 1,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 0,
    sinkCount: 0,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  bathroom: {
    spaceType: 'bathroom',
    name: 'Standard Bathroom / Toilet',
    defaultLengthFt: 6.0,
    defaultWidthFt: 5.0,
    defaultAreaSqFt: 30.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 1,
    windowAreaSqFt: 6.0,
    doorOpeningAreaSqFt: 17.5,
    lightPoints: 2,
    fanPoints: 0,
    socketPoints: 2,
    acPoints: 0,
    geyserPoints: 1,
    tvDataPoints: 0,
    waterPoints: 4,
    drainagePoints: 2,
    wcCount: 1,
    washBasinCount: 1,
    showerCount: 1,
    healthFaucetCount: 1,
    floorDrainCount: 1,
    sinkCount: 0,
    isWetArea: true,
    waterproofingUpturnFt: 1.0,
    source: 'Minutes of Meeting (September 19, 2026)',
    requiresClientConfirmation: false,
  },
  commonToilet: {
    spaceType: 'commonToilet',
    name: 'Common Toilet / Powder Room',
    defaultLengthFt: 5.0,
    defaultWidthFt: 4.0,
    defaultAreaSqFt: 20.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 1,
    windowAreaSqFt: 6.0,
    doorOpeningAreaSqFt: 17.5,
    lightPoints: 2,
    fanPoints: 0,
    socketPoints: 2,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 3,
    drainagePoints: 2,
    wcCount: 1,
    washBasinCount: 1,
    showerCount: 0,
    healthFaucetCount: 1,
    floorDrainCount: 1,
    sinkCount: 0,
    isWetArea: true,
    waterproofingUpturnFt: 1.0,
    source: 'Minutes of Meeting (September 19, 2026)',
    requiresClientConfirmation: false,
  },
  kitchen: {
    spaceType: 'kitchen',
    name: 'Kitchen Space',
    defaultLengthFt: 10.0,
    defaultWidthFt: 9.0,
    defaultAreaSqFt: 90.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 1,
    windowAreaSqFt: 12.0,
    doorOpeningAreaSqFt: 21.0,
    lightPoints: 3,
    fanPoints: 1,
    socketPoints: 5,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 2,
    drainagePoints: 1,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 1,
    sinkCount: 1,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  living: {
    spaceType: 'living',
    name: 'Living Room / Hall',
    defaultLengthFt: 16.0,
    defaultWidthFt: 12.5,
    defaultAreaSqFt: 200.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 0,
    windowRequirement: 2,
    windowAreaSqFt: 60.0,
    doorOpeningAreaSqFt: 0.0,
    lightPoints: 6,
    fanPoints: 2,
    socketPoints: 6,
    acPoints: 1,
    geyserPoints: 0,
    tvDataPoints: 2,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 0,
    sinkCount: 0,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  dining: {
    spaceType: 'dining',
    name: 'Dining Area',
    defaultLengthFt: 12.0,
    defaultWidthFt: 10.0,
    defaultAreaSqFt: 120.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 0,
    windowRequirement: 1,
    windowAreaSqFt: 15.0,
    doorOpeningAreaSqFt: 0.0,
    lightPoints: 3,
    fanPoints: 1,
    socketPoints: 2,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 0,
    sinkCount: 0,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  balcony: {
    spaceType: 'balcony',
    name: 'Balcony / Verandah',
    defaultLengthFt: 10.0,
    defaultWidthFt: 5.0,
    defaultAreaSqFt: 50.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 0,
    windowAreaSqFt: 0.0,
    doorOpeningAreaSqFt: 21.0,
    lightPoints: 1,
    fanPoints: 0,
    socketPoints: 1,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 1,
    sinkCount: 0,
    isWetArea: true,
    waterproofingUpturnFt: 0.5,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  utility: {
    spaceType: 'utility',
    name: 'Utility / Service Area',
    defaultLengthFt: 8.0,
    defaultWidthFt: 5.0,
    defaultAreaSqFt: 40.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 1,
    windowAreaSqFt: 8.0,
    doorOpeningAreaSqFt: 17.5,
    lightPoints: 1,
    fanPoints: 0,
    socketPoints: 2,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 1,
    drainagePoints: 1,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 1,
    sinkCount: 0,
    isWetArea: true,
    waterproofingUpturnFt: 0.5,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  pooja: {
    spaceType: 'pooja',
    name: 'Pooja Room',
    defaultLengthFt: 5.0,
    defaultWidthFt: 5.0,
    defaultAreaSqFt: 25.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 0,
    windowAreaSqFt: 0.0,
    doorOpeningAreaSqFt: 17.5,
    lightPoints: 1,
    fanPoints: 0,
    socketPoints: 1,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 0,
    sinkCount: 0,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  office: {
    spaceType: 'office',
    name: 'Study / Home Office',
    defaultLengthFt: 10.0,
    defaultWidthFt: 10.0,
    defaultAreaSqFt: 100.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 1,
    windowAreaSqFt: 15.0,
    doorOpeningAreaSqFt: 21.0,
    lightPoints: 3,
    fanPoints: 1,
    socketPoints: 4,
    acPoints: 1,
    geyserPoints: 0,
    tvDataPoints: 1,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 0,
    sinkCount: 0,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
  storeRoom: {
    spaceType: 'storeRoom',
    name: 'Store Room',
    defaultLengthFt: 7.0,
    defaultWidthFt: 5.0,
    defaultAreaSqFt: 35.0,
    clearWallHeightFt: 10.0,
    doorRequirement: 1,
    windowRequirement: 0,
    windowAreaSqFt: 0.0,
    doorOpeningAreaSqFt: 17.5,
    lightPoints: 1,
    fanPoints: 0,
    socketPoints: 1,
    acPoints: 0,
    geyserPoints: 0,
    tvDataPoints: 0,
    waterPoints: 0,
    drainagePoints: 0,
    wcCount: 0,
    washBasinCount: 0,
    showerCount: 0,
    healthFaucetCount: 0,
    floorDrainCount: 0,
    sinkCount: 0,
    isWetArea: false,
    waterproofingUpturnFt: 0,
    source: 'Hutty Pilot Spec (Section 4)',
    requiresClientConfirmation: true,
  },
};

export const HUTTY_BASELINE_COMMERCIAL: CommercialRuleConfig = {
  contractorMarginDefault: 0.10, // 10% in contractor mode
  contingencyRateDefault: 0.00,
  professionalFeesRateDefault: 0.05,
  gstRateDefault: 0.18,
  selfBuildMarginRate: 0.00,
  selfBuildContingencyRate: 0.00,
  selfBuildProfessionalFeesRate: 0.00,
  selfBuildGstRate: 0.00,
};

export const HUTTY_BASELINE_LABOUR_BENCHMARKS: Record<string, LabourBenchmarkConfig> = {
  civil_composite: {
    tradeKey: 'labour.civil_composite',
    tradeName: 'Composite Civil & Structural Labour Package',
    category: 'Civil & Structure',
    basis: 'Total Built-Up Area',
    unit: '₹/SqFt',
    rates: {
      Bangalore_Standard: 350,
      Bangalore_Premium: 380,
      Bangalore_Luxury: 400,
      Mysore_Standard: 310,
      Mysore_Premium: 335,
      Mysore_Luxury: 350,
    },
    source: 'Minutes of Meeting (September 19, 2026)',
  },
  electrical_point: {
    tradeKey: 'labour.electrical_point',
    tradeName: 'Electrical Point Wiring & Distribution Labour',
    category: 'Electrical',
    basis: 'Electrical Points Schedule',
    unit: '₹/Point',
    rates: {
      ALL_Standard: 100,
      ALL_Premium: 120,
      ALL_Luxury: 140,
    },
    source: 'Hutty Pilot Spec (Section 19)',
  },
  plumbing_toilet: {
    tradeKey: 'labour.plumbing_toilet',
    tradeName: 'Plumbing, Water Supply & Sanitary Installation Labour',
    category: 'Plumbing',
    basis: 'Bathroom / Wet Core Units',
    unit: '₹/Unit',
    rates: {
      ALL_Standard: 6000,
      ALL_Premium: 7200,
      ALL_Luxury: 8500,
    },
    source: 'Hutty Pilot Spec (Section 20)',
  },
  flooring_tiling: {
    tradeKey: 'labour.flooring_tiling',
    tradeName: 'Flooring & Wall Dado Tile Laying Labour',
    category: 'Flooring & Tiling',
    basis: 'Floor & Wall Tile Area',
    unit: '₹/SqFt',
    rates: {
      ALL_Standard: 32,
      ALL_Premium: 38,
      ALL_Luxury: 45,
    },
    source: 'Hutty Pilot Spec (Section 15, 16)',
  },
  painting_finishes: {
    tradeKey: 'labour.painting_finishes',
    tradeName: 'Painting & Surface Preparation Labour',
    category: 'Painting & Finishes',
    basis: 'Paintable Surface Area',
    unit: '₹/SqFt',
    rates: {
      ALL_Standard: 14,
      ALL_Premium: 18,
      ALL_Luxury: 22,
    },
    source: 'Hutty Pilot Spec (Section 17)',
  },
  waterproofing_app: {
    tradeKey: 'labour.waterproofing_app',
    tradeName: 'Waterproofing Chemical Treatment Labour',
    category: 'Waterproofing',
    basis: 'Treated Surface Area',
    unit: '₹/SqFt',
    rates: {
      ALL_Standard: 18,
      ALL_Premium: 18,
      ALL_Luxury: 22,
    },
    source: 'Hutty Pilot Spec (Section 23)',
  },
};
